name: ✨ Feature Request
description: Suggest a new feature or enhancement for Liquid UI
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.
        
  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Component
        - Component Enhancement
        - API Enhancement
        - Performance Improvement
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: "I'm frustrated when..."
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "I would like to see..."
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: "I've also considered..."
      
  - type: textarea
    id: examples
    attributes:
      label: Examples and References
      description: Provide examples of similar features in other libraries or designs
      placeholder: |
        - Material-UI has something similar: [link]
        - Apple's design shows: [description]
        - Other libraries: [examples]
        
  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        1. When building a dashboard...
        2. For mobile responsive design...
        3. In accessibility scenarios...
    validations:
      required: true
      
  - type: textarea
    id: api-design
    attributes:
      label: API Design (if applicable)
      description: If this is a component or API change, suggest how it should work
      render: typescript
      placeholder: |
        // Example API design
        <LiquidNewComponent
          variant="frosted"
          intensity="regular"
          onInteraction={(data) => {}}
        >
          Content
        </LiquidNewComponent>
        
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would improve my workflow"
        - "High - Blocking my work"
        - "Critical - Can't ship without it"
    validations:
      required: true
      
  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - "Simple - A few hours of work"
        - "Medium - A few days of work"
        - "Complex - Weeks of development"
        - "Major - Requires significant planning"
        - "I'm not sure"
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request
      
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to work on this feature
        - label: I can help with testing
        - label: I can help with documentation
        - label: I can provide feedback during development
        
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions to avoid duplicates
          required: true
        - label: This feature aligns with Liquid UI's goals of Apple-style glass effects
          required: true
        - label: I understand this is a request and may not be implemented immediately
          required: true