name: Deploy to Google Cloud

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  DOMAIN: liquid-ui.strayeye.com

jobs:
  build-and-deploy:
    name: Build and Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --coverage --passWithNoTests
        env:
          CI: true

      - name: Build packages
        run: npm run build

      - name: Build demo app
        run: npm run build
        working-directory: apps/demo
        env:
          NEXT_PUBLIC_SITE_URL: https://${{ env.DOMAIN }}
          NODE_ENV: production

      - name: Build Storybook
        run: npm run build-storybook
        working-directory: apps/storybook

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ env.GCP_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/liquid-ui:${{ github.sha }} .
          docker tag gcr.io/${{ env.GCP_PROJECT_ID }}/liquid-ui:${{ github.sha }} gcr.io/${{ env.GCP_PROJECT_ID }}/liquid-ui:latest

      - name: Push to Container Registry
        run: |
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/liquid-ui:${{ github.sha }}
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/liquid-ui:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy liquid-ui \
            --image gcr.io/${{ env.GCP_PROJECT_ID }}/liquid-ui:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 3000 \
            --memory 2Gi \
            --cpu 2 \
            --max-instances 20 \
            --min-instances 1 \
            --timeout 300 \
            --set-env-vars NODE_ENV=production \
            --set-env-vars NEXT_PUBLIC_SITE_URL=https://${{ env.DOMAIN }}

      - name: Configure domain mapping
        run: |
          gcloud run domain-mappings create \
            --service liquid-ui \
            --domain ${{ env.DOMAIN }} \
            --region us-central1 \
            --platform managed || echo "Domain mapping already exists"

      - name: Get service URL
        id: get-url
        run: |
          SERVICE_URL=$(gcloud run services describe liquid-ui --region us-central1 --format 'value(status.url)')
          echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_OUTPUT
          echo "Deployed to: $SERVICE_URL"

      - name: Warm up the service
        run: |
          sleep 30
          curl -f https://${{ env.DOMAIN }} || echo "Service warming up..."
          
      - name: Run smoke tests
        run: |
          # Simple health check
          curl -f https://${{ env.DOMAIN }} -H "User-Agent: GitHub-Actions-Health-Check"
          
          # Check if Storybook is accessible (if deployed)
          # curl -f https://${{ env.DOMAIN }}/storybook || echo "Storybook not accessible"

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            Automated release from main branch
            
            **Deployed to:** https://${{ env.DOMAIN }}
            **Commit:** ${{ github.sha }}
            
            ## Changes
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Notify deployment success
        if: success()
        run: |
          echo "✅ Deployment successful!"
          echo "🌐 Live at: https://${{ env.DOMAIN }}"
          echo "📝 Commit: ${{ github.sha }}"
          echo "🏷️ Release: v${{ github.run_number }}"

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Deployment failed!"
          echo "📝 Commit: ${{ github.sha }}"
          echo "🔍 Check logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"